/***
{smcl}
{* *! version 2.0.0  26aug2016}{...}
{marker topic}
{helpb nw_topical##analysis_statmodels:[NW-2.6.6] Statistical Estimation of Networks}

{title:Title}

{p2colset 9 20 23 2}{...}
{p2col :nwcorrelate {hline 2}}Correlate networks and variables{p_end}
{p2colreset}{...}


{title:Syntax}

     1) Correlate nodes of a network
		
{p 8 17 2}
{cmdab: nwcorrelate} 
{it:{help netname:netname}}
[,
{opt context}({it:{help nwcontext##context:context}})
{opth name(newnetname)}]


     2) Correlate two networks with each other

{p 8 17 2}
{cmdab: nwcorrelate} 
{it:{help netname:netname1}}
{it:{help netname:netname2}}
[,
{opth permutations(int)}
{opth save(filename)}
{it:{help kdensity:kdensity_options}}]


     3) Correlate one network and one variable
		
{p 8 17 2}
{cmdab: nwcorrelate} 
{it:{help netname:netname}}
, 
{opth attribute(varname)}
[{opt mode}({it:{help nwexpand##expand_mode:expand_mode}})
{opt name}({it:{help newnetname}})
{opt keepexpand}
{opth permutations(int)}
{opth save(filename)}
{it:{help kdensity:kdensity_options}}]


{synoptset 30 tabbed}{...}
{synopthdr}
{synoptline}
{synopt:{opt context}({it:{help nwcontext##context:context})}}Determines whether incoming or outgoing ties should be considered when correlating two nodes; default = {it:both}{p_end}
{synopt:{opth name(newnetname)}}Name of new network with node correlations; default = {it:_corr}{p_end}
{synopt:{opt mode}({it:{help nwexpand##expand_mode:expand_mode})}}How to expand the attribute variable{p_end}
{synopt:{opt keepexpand}}Keep the network generated by {help nwexpand}{p_end}
{synopt:{opt permutations(integer)}}Number of QAP permuations{p_end}
{synopt:{opth save(filename)}}Save QAP permuation results in file{p_end}


{title:Description}

{pstd}
This command is the network version of {help correlate}. It can be used in three different ways:

{pmore}
1) Correlate nodes of a network

{pmore}
2) Correlate two networks with each other

{pmore}
3) Correlate one network and one variable

{pstd}
The option {bf:permutation()} creates {help nwqap:QAP permutations} of the first network and 
generates a distribution of correlation coefficients under the null-hypothesis that there is
no correlation. In practice, rows and columns of {help netname} are reshuffled and the correlation 
coefficient is calculated again and again. Based on this distribution a {it:p-value} and a confidence
interval is calculated. A plot is displayed and additional information is returned in the return vector. 

{marker nodes}{...}
{title:Nodes of one network}

{pstd}
When the command is used with one {help netname} and no {opt attribute()} option, it correlates the nodes of 
a network with each other. It takes the vector of outgoing, incoming (or both) ties of node {it:i} and correlates it 
with the vector of outgoing, incoming (or both) ties of node {it:j}. The context is specified in {opt context()}. 

{pstd}
The nodes {it:i} and {it:j} are excluded from the tie vectors when calculating the correlation between {it:i} and
{it:j}. For the network called {it: mynet} defined by the adjacency matrix in the following example, the command

{pmore}
{bf: nwcorrelate mynet, context(outgoing)}

{pstd}
produces the correlation matrix below (saved as a new network). In this
case only the outgoing ties are considered. For example, the score C[2,1] = 0.5 is the correlation of the two row
vectors for node 2 {it:(1,0,1,1) => (.,.,1,1)} and node 1 {it:(0,1,1,0) => (.,.,1,0)}. Notice that 
the nodes {it:i} and {it:j} are removed from the vectors.

{pstd}
The correlation {it:C_ij} between two nodes is 1 when the nodes {it:i} and {it:j} have exactly the same network
neighbors. The coefficient is -1 when the two nodes have no network neighbors in common.  

{pstd}
{bf:Adjacency matrix of network {it:mynet}}

{res}       {txt}1   2   3   4
    {c TLC}{hline 17}{c TRC}
  1 {c |}  {res}0   1   1   0{txt}  {c |}
  2 {c |}  {res}1   0   1   1{txt}  {c |}
  3 {c |}  {res}0   0   0   0{txt}  {c |}
  4 {c |}  {res}0   1   0   0{txt}  {c |}
    {c BLC}{hline 17}{c BRC}
	
{pstd}
{bf: Correlation between nodes}

        1    2    3    4
    {c TLC}{hline 21}{c TRC}
  1 {c |}  {res} 1               {txt}  {c |}
  2 {c |}  {res}.5    1          {txt}  {c |}
  3 {c |}  {res}-1   -1    1     {txt}  {c |}
  4 {c |}  {res}.5   -1   -1    1{txt}  {c |}
    {c BLC}{hline 21}{c BRC}

{pstd}
In this example, we first load the data from Zachary's Karate Club (saved in Ucinet format). These are 
data collected from the members of a university karate club by  Wayne Zachary (1977). The ZACHE network represents 
the presence or absence of ties among the members of the club; the ZACHC network indicates the relative
strength of the associations (number of situations in and outside the club in which interactions 
occurred).

{pmore}
{cmd:. nwimport http://vlado.fmf.uni-lj.si/pub/networks/data/ucinet/zachary.dat, type(ucinet)}

{pstd}
Next, let us calculate the correlation between nodes (which essentially gives us an idea about the overlap of 
ties between nodes). Remember that the correlation between two nodes is 1 when these two nodes share exactly
the same network neighbors. 

{pmore}
{cmd:. nwcorrelate ZACHE}

{pstd}
This generates the new network {it:_corr}, which holds the pair-wise node correlations. These node correlations tell us
how many friends two nodes i and j have in common. Now we can test
if ties between nodes are more likely when these nodes have many common network neighbors.

{pmore}
{cmd:. nwcorrelate ZACHE _corr, permutations(200)}

{pstd}
Basically, we just proofed one part of Granovetter's (1973) strength of weak ties argument. It seems that ties
between two nodes are more likely to exist when these nodes share many network neighbors.



{title:Two networks}

{pstd}
When two networks {help netname:netname1} and {help netname:netname2} are given, 
the command calculates the correlation of the underlying adjaceny matrices {it:M1}
and {it:M2} for the two networks. Notice, that the diagonal of the matrices are not considered. 

{pstd}
The correlation coefficient for two networks indicates how much these two networks overlap. It is exactly
1 when the two networks completely overlap ({it:M1_ij == M2_ij}). It is -1 when the two networks are inverse
to each other ({it:M1_ij != M2_ij}).

{pstd}
This correlates two networks with each other:

	{cmd:. nwwebuse florentine}
	{cmd:. nwcorrelate flomarriage flobusiness, permutations(50)}

	{res}{hline 40}
	{txt}  Network name: {res}flomarriage
	{txt}  Network2 name: {res}flobusiness
	{hline 40}
	{txt}    Correlation: {res}.372{txt}
	{txt}    P-value: 0{txt}
	
{pstd}
In this case, there is a moderate positive correlation between the two networks, i.e. ties in the business network are
more likely when there are ties in the marriage network.

	
{title:One network and one attribute}

{pstd}
When the command is called with one {help netname} and one {help varname} (specified in {bf:attribute()})
it calculates the element-by-element correlation between the adjacency matrix {it:M} of {help netname} and 
an {help nwexpand:expanded network} based on {help varname}. 

{pstd}
Practically, it compares {it:M_ij} with {it:x_ij}, where

	{it:x_ij = mode(varname[i], varname[j])}

{pstd}	
By default, {it:mode} is set to {cmd:mode(same)}, which is (for other modes see {help nwexpand}):

	{it:same(x_ij) = (varname[i] == varname[j])}

{pstd}
Such dyad-level correlation between network ties and some artifically generated network based on some variable,
can be extremely useful to e.g. assess the level of homphily in a network. Homophily refers to the concept that
network ties might be more likely between similar individuals. 

{pstd}
The correlation coefficient between a network and a variable (with {it:mode=same}) is exactly 1 when ties 
only exist between individuals who are similar and -1 when ties only exist between individuals who are different
according to {help varname}. When an attribute is not categorical, but metric instead, it makes a lot of sense to 
use option {bf:mode(absdist)}.
	
{pstd}
This correlates one network and one attribute with each other:

    {cmd:. nwwebuse glasgow}
	{cmd:. nwcorrelate glasgow1, attribute(sport1) permutations(50)}

	{res}{hline 40}
	{txt}  Network name: {res}glasgow1
	{txt}  Attribute: {res}same_sport1
	{hline 40}
	{txt}    Correlation: {res}.0253{txt}

	
{pstd}
There is hardly any correlation. Similarity on doing sports does not seem to matter for indivdiuals to have
friendship ties. Notice that the previous command is equivalent to:

	{cmd:. nwexpand sport1, mode(same) name(same_sport)}
	{cmd:. nwcorrelate glasgow1 same_sport, permutations(50)}	


	
{title:References}

{pstd}
Granovetter, M. (1973). The strength of weak ties. American Journal of Sociology, 78, 6, 1360-1380.

{pstd}
Zachary, W. (1977). An information flow model for conflict and fission in
small groups. Journal of Anthropological Research, 33, 452-473.


{title:Stored results}

{pstd}
{bf:Node correlations}

	Scalars:
	  {bf:r(avg_corr)}	average correlation coefficient between nodes

	Macros:
	  {bf:r(name)}	name of network
	  {bf:r(corrname)}	name of new network with coefficients

	  
{pstd}
{bf:Two networks or one network and one attribute}

	Scalars:
	  {bf:r(corr)}		correlation coefficient
	  {bf:r(pvalue)}	p-value of correlation coefficient
	  {bf:r(ub)}		upper bound, 95% confidence interval
	  {bf:r(lb)}		lower bound, 95% confidence interval

	Macros:
	  {bf:r(name_1)}	name of {it:netname1}
	  {bf:r(name_2)}	name of {it:netname2} or the expanded network 
	  

{title:See also}

	{help nwtabulate}, {help nwexpand}

***/

capture program drop nwcorrelate
program nwcorrelate
	syntax [anything] [, attribute(string) * ]
	
//(string) attribute(string) name(string) permutations(integer 100) save(string) ] 
	
	nw_syntax `anything', min(1) max(2)

	if "`attribute'"!= "" {
		local netname : word 1 of `netname'
		nwcorrelate_nets `netname', attribute(`attribute') `options'
	}
	if `networks' == 2 {
		nwcorrelate_nets `netname' , `options' 
	}
	if `networks' == 1 & "`attribute'" == ""{
		nwcorrelate_nodes `netname', `options'
	}
end

capture program drop nwcorrelate_nodes
program nwcorrelate_nodes
	syntax [anything(name=netname)] [, name(string) context(string)]
	nw_syntax `netname'
	if "`context'" == "" {
		local context = "outgoing"
	}
	_opts_oneof "outgoing incoming both" "context" "`context'" 6556
	
	if "`name'" == "" {
		local name = "_corr"
	}
	
	capture nwdrop `name'

	if "`context'" == "outgoing" {
		local neighborhood = 1
	}
	if "`context'" == "incoming" {
		local neighborhood = 2
	}
	if "`context'" == "both" {
		local neighborhood = 3
	}

	nw_syntax `netname'
	local origname "`netname'"
	
	nwset, mat(`netobj'->correlate_nodes(`neighborhood')) name("`name'")	
	nw_syntax
	
	mata: st_rclear()
	mata: st_numscalar("r(avg_corr)", ( sum(*`netobj'->get_matrix()) / sum((*`netobj'->get_matrix()):!=.)))
	
	mata: st_global("r(name)", "`origname'")
	mata: st_global("r(corrname)", "`netname'")
	mata: st_global("r(context)", "`context'")
	di 
	di "{txt}  Network name: {res}`r(name)'"
	di "{txt}  Correlation network: {res}`r(corrname)'"
	di "{hline 40}"
	di "{txt}    Context definition: {res}`r(context)'"
	di "{txt}    Average correlation between nodes: {res}`=round(`r(avg_corr)',0.001)'"
end


capture program drop nwcorrelate_nets	
program nwcorrelate_nets
syntax [anything(name=netnames)] [, ifcond(string) keepexpand context(string) mode(string) ATTRibute(string) PERMutations(integer 1) SAVe(string asis) *]
	
	if "`mode'" == "" {
		local mode = "same"
	}
	
	nw_syntax `netnames', max(2) min(1)
	local netname1 : word 1 of `netname'
	local netname2 : word 2 of `netname'
	
	nw_datasync `netname1'
	
	nw_syntax `netname1'
	local netnodes1 `nodes'
	local netobj1 `netobj'
	
	if "`attribute'" != "" {
		confirm variable `attribute'
		capture nwdrop `mode'_`attribute'
		nwexpand `attribute', nodes(`netnodes1') network(`netname1') mode(`mode') name(`mode'_`attribute')
		local netname2 = "`mode'_`attribute'"
	}
	
	nw_syntax `netname2'
	local netnodes2 `nodes'
	local netobj2 `netobj'
	
	if `netnodes1' != `netnodes2' {
		di "{err}Networks of different size.{txt}"
		error 100
	}
	
	
	local bandwidth `= 1 / `netnodes1''

	// Return the names and id's of the networks that are correlated with each other.
	mata: st_rclear()
	mata: st_global("r(name_2)", "`netname2'")
	mata: st_global("r(name_1)", "`netname1'")
	
	// Calculate correlation of two networks.
	mata: st_numscalar("r(corr)",correlate_nets((*`netobj1'->get_matrix()), (*`netobj2'->get_matrix()))	)
	local corr `r(corr)'
	
	// Calculate correlations of network2 with permutations of network1
	if (`permutations' > 1) {
		mata: corr_reps = correlate_nets_rep(`permutations', (*`netobj1'->get_matrix()), (*`netobj2'->get_matrix()))
		capture _return drop _all
		tempname myr
		_return hold `myr'
		
		preserve
		drop _all
		
		getmata correlation = corr_reps
		capture mata: mata drop corr_reps
		
		gen observed = r(corr)
		if "`save'"!= "" {
			di "QAP results saved as: `c(pwd)'/nwcorrelationqap.dta" 
			save "`save'", replace
		}
	
		qui count
		local count_total `r(N)'

		if `corr' > 0 {
			qui count if correlation >= `corr'
		}
		else {
			qui count if correlation <= `corr'	
		}
		local count_out `r(N)'
		
		mata: _pvalue = `count_out' / `count_total'
		
		_pctile correlation, percentiles(2.5 97.5)
		mata: _lb = `r(r1)'
		mata: _ub = `r(r2)'
		
		qui sum correlation
		local xmin = r(min)
		local xmax = r(max)
		
		if `corr' < `xmin' {
			local xmin = `corr'
		}
		if `corr' > `xmax' {
			local xmax = `corr'
		}
		
		kdensity correlation, xscale(range(`xmin' `xmax')) bwidth(`bandwidth') title("Corr(`netname1', `netname2')") ytitle("density") xline(`corr',lpattern(dash)) xlabel(#5) note(`"based on `permutations' QAP permutations of network `net1'"') `options'	

		restore
		_return restore `myr'
	
		mata: st_numscalar("r(lb)", _lb)
		mata: st_numscalar("r(ub)", _ub)
		mata: st_numscalar("r(pvalue)", _pvalue)
		capture mata: mata drop _lb _ub _pvalue
	}
	capture mata: mata drop ifmata
	
	di "{hline 40}"
	di "{txt}  Network1 name: {res}`r(name_1)'"
	di "{txt}  Network2 name: {res}`r(name_2)'"
	
	di "{hline 40}"
	di "{txt}    Correlation: {res}`=round(`r(corr)',0.001)'"
	if "`r(pvalue)'" != "" {
		di "{txt}    P-value: {res}`=round(`r(pvalue)',0.001)'"
	}
	_return hold r1
	if "`attribute'" != "" {
		if "`keepexpand'" == "" {
			capture nwdrop `netname2'
		}
	}
	_return restore r1
end





